# Generated by Django 4.2.4 on 2023-08-30 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='age',
            new_name='userAge',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='sex',
            new_name='userSex',
        ),
    ]
